config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :dogs
  resources :nicknames
  get '/login',        to: 'sessions#new'
  post '/login',       to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  post '/search',  to: 'users#search'
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many :nicknames
  has_and_belongs_to_many :roles  
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]
  before_action :set_roles, only: [:new, :show, :edit, :update]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
    @new_nickname = Nickname.new(dog_id: @dog.id)
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    def set_roles
      @roles = Role.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name,:image_url, role_ids:[])
    end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= form_with(model: dog, local: true) do |form| %>
  <% if dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :dog_name %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :image_url %>
  </div>

  <h1>Roles</h1>
  <%= form.collection_check_boxes( :role_ids, @roles, :id, :role_name) do |b| %>
  <div class="checkbox">
    <%= b.label(class: "checkbox") { b.check_box(checked: (dog.role_ids.include? b.value), class: "add_margin") + b.text } %>
  </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <% if !@dog.image_url.nil? && @dog.image_url.length > 0 %>
    <img src="<%= @dog.image_url %>" width="100" />
  <% else %>
    <%= image_tag "default-dog.png", width: "100" %>
  <% end %>
  <strong>Name:</strong>
  <%= @dog.name %>
</h1>
<p>This is including the image via an image url if provided,
   otherwise shows a default image</p>
<p>For image upload option see <%= link_to "textbook Ch 13.4.1", 'https://www.railstutorial.org/book/user_microposts#sec-basic_image_upload',style: "text-decoration:underline" %> </p>

<h2>Nicknames</h2>
<table width="100%" border="1">
  <thead>
    <tr>
      <th width="75%">Nickname</th>
      <th width="25%"></th>
    </tr>
  </thead>

  <tbody>
    <% @dog.nicknames.each do |nickname| %>
      <tr>
          <td><%= nickname.name %></td>
          <td><%= link_to 'Show', nickname %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Add a new nickname</h1>
<%= form_with(model: @new_nickname, local: true) do |form| %>
  <%= hidden_field_tag('nickname[dog_id]', @dog.id) %>
  <%= hidden_field_tag('add_nickname', 'true') %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :nickname_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>




<h2>Roles</h2>
<table width="100%" border="1">
  <thead>
    <tr>
      <th width="75%">Roles</th>
      <th width="25%"></th>
    </tr>
  </thead>

  <tbody>
    <% @dog.roles.each do |role| %>
      <tr>
          <td><%= role.role_name %></td>
          <td><%= link_to 'Show', role %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>