config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :dogs
  resources :nicknames
  get '/login',        to: 'sessions#new'
  post '/login',       to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  post '/search',  to: 'users#search'
end

app/models/nickname.rb
class Nickname < ApplicationRecord
  belongs_to :dog
end

app/controllers/nicknames_controller.rb
class NicknamesController < ApplicationController
  before_action :set_nickname, only: [:show, :edit, :update, :destroy]
  before_action :set_dogs, only: [:new, :show, :edit, :update]

  # GET /nicknames
  # GET /nicknames.json
  def index
    @nicknames = Nickname.all
  end

  # GET /nicknames/1
  # GET /nicknames/1.json
  def show
  end

  # GET /nicknames/new
  def new
    @nickname = Nickname.new
  end

  # GET /nicknames/1/edit
  def edit
  end

  # POST /nicknames
  # POST /nicknames.json
  def create
    @nickname = Nickname.new(nickname_params)

    # If adding a nickname to a dog from that page redirect there
    if !params[:add_nickname].nil?
      @nickname.save
      flash[:success] = 'Nickname added!'
      redirect_to @nickname.dog
    else
      respond_to do |format|
        if @nickname.save
          format.html { redirect_to @nickname, notice: 'Nickname was successfully created.' }
          format.json { render :show, status: :created, location: @nickname }
        else
          format.html { render :new }
          format.json { render json: @nickname.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /nicknames/1
  # PATCH/PUT /nicknames/1.json
  def update
    respond_to do |format|
      if @nickname.update(nickname_params)
        format.html { redirect_to @nickname, notice: 'Nickname was successfully updated.' }
        format.json { render :show, status: :ok, location: @nickname }
      else
        format.html { render :edit }
        format.json { render json: @nickname.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nicknames/1
  # DELETE /nicknames/1.json
  def destroy
    @nickname.destroy
    respond_to do |format|
      format.html { redirect_to nicknames_url, notice: 'Nickname was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nickname
      @nickname = Nickname.find(params[:id])
    end

    def set_dogs
      @dogs = Dog.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nickname_params
      params.require(:nickname).permit(:name, :dog_id)
    end
end

app/helpers/nicknames_helper.rb
module NicknamesHelper
end

app/views/nicknames/_form.html.erb
<%= form_with(model: nickname, local: true) do |form| %>
  <% if nickname.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nickname.errors.count, "error") %> prohibited this nickname from being saved:</h2>

      <ul>
      <% nickname.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :nickname_name %>
  </div>

  <div class="field">
    <%= form.label :dog_id %>
    <%= form.collection_select(:dog_id, @dogs, :id, :name) %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nicknames/edit.html.erb
<h1>Editing Nickname</h1>

<%= render 'form', nickname: @nickname %>

<%= link_to 'Show', @nickname %> |
<%= link_to 'Back', nicknames_path %>

app/views/nicknames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nicknames</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dog</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nicknames.each do |nickname| %>
      <tr>
        <td><%= nickname.name %></td>
        <td><%= link_to nickname.dog.name, nickname.dog %></td>
        <td><%= link_to 'Show', nickname %></td>
        <td><%= link_to 'Edit', edit_nickname_path(nickname) %></td>
        <td><%= link_to 'Destroy', nickname, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nickname', new_nickname_path %>

app/views/nicknames/new.html.erb
<h1>New Nickname</h1>

<%= render 'form', nickname: @nickname %>

<%= link_to 'Back', nicknames_path %>

app/views/nicknames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @nickname.name %>
</p>

<p>
  <strong>Dog:</strong>
  <%= @nickname.dog_id %>
</p>

<%= link_to 'Edit', edit_nickname_path(@nickname) %> |
<%= link_to 'Back', nicknames_path %>